config/routes.rb
Physicsninja::Application.routes.draw do
  resources :users do
    resources :purchases, only: :index
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :questions do
    resources :responses, only: [:create, :index, :destroy]
    resources :comments,  only: [:create, :index, :destroy]
  end
  resources :plans,       only: :index
  resources :purchases,   only: [:show, :new, :create, :destroy]
  resources :ninjas,      only: [:new, :create]

  resources :examples,    only: :show

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/buy',     to: 'plans#index'

  match '/pending',   to: 'questions#pending'
  match '/answered',  to: 'questions#answered'
  match '/commented', to: 'questions#commented'

  match 'users/:id/toggle_admin', to: 'users#toggle_admin'
  match 'users/:id/toggle_ninja', to: 'users#toggle_ninja'
  match 'users/:id/give_q',       to: 'users#give_q'

  match '/support', to: 'static_pages#support'
  match '/about',   to: 'static_pages#about'
  match '/admin',   to: 'static_pages#admin'
  match '/how_it_works',   to: 'static_pages#howitworks'
  match '/why_we_charge',   to: 'static_pages#whywecharge'
  match '/ninja_code',   to: 'static_pages#ninjacode'
  match '/unsubscribe',   to: 'static_pages#unsubscribe'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :admin_user, only: [:admin]
  
  def home
  	if signed_in?
      @user = current_user
      if current_user.ninja?
        @pending_items = Question.where("id not in (?)", Question.joins(:responses))
        @new_comment_items = current_user.new_comment.paginate(page: params[:page])
      else
        @question = current_user.questions.build
        @answered_items = current_user.answered.paginate(page: params[:page])
    		@pending_items = current_user.pending.paginate(page: params[:page])
        @example = Example.first
      end
  	end
  end

  def support
  end

  def about
  end

  def admin
    @installs = User.all
    @pending_items = Question.where("id not in (?)", Question.joins(:responses))
    @answered_items = Question.where("id in (?)", Question.joins(:responses))
    @new_comment_items = Question.last_comments.where("comments.user_id not in (?)", User.where(ninja: true)).group("questions.id")
  end

  def howitworks
  end

  def whywecharge
  end

  def ninjacode
  end

  def unsubscribe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="center">
	<h1>About</h1>
	<h2> Nice try, grasshopper.</h2>
</div>
<p>
  We can't disclose the Ninja's origins. Though we can tell you hilarious facts on <%= link_to "twitter", '#' %>.
  <br>
  If something's wrong, learn how to get help on the <%= link_to "support", support_path %> page.
  <br>
  You can also learn more about how the ninja works <%= link_to "here", how_it_works_path %>.
</p>

app/views/static_pages/admin.html.erb
<% if signed_in? %>
  <% if current_user.admin? %>
  	<% provide(:title, 'Admin') %>
  	<h1>Admin</h1>
  	<h4><%= link_to "Users:", users_path %> <%= @installs.count %></h4>
  	<h4><%= link_to "Pending Questions:", pending_path %> <%= @pending_items.count %></h4>
  	<h4><%= link_to "Questions with new user comments:", commented_path %> <%= @new_comment_items.all.count %></h4>
  	<h4><%= link_to "Answered Questions:", answered_path %> <%= @answered_items.count %></h4>
  <% end %>
<% end %>

app/views/static_pages/help.html.erb
Help page

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% content_for :head do %>
  <meta name = "description" content = "On-demand answers to any physics question. Get high-quality help on homework with explanations and solutions you can actually understand!" />
  <meta name = "keywords" content = "physics, homework, help, questions, answers, solutions, tutor, tutoring" />
<% end %>

<% if signed_in? %>
  <% if current_user.ninja? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info'%>
        </section>
          <br>
          <span>
            <% if @new_comment_items.any? %>
              <%= link_to "You have new comments to view!", current_user, class: "new_comment_button" %>
            <% else %>
              <%= link_to "View your answers", current_user, class: "btn btn-large btn-primary" %>
            <% end %>
          </span>
        </section>
      </aside>
      <div class="span8">
        <h3>New questions <i>(<%= @pending_items.count %>)</i></h3>
        <ul class="questions">
          <%= render 'shared/pending' %>
        </ul>
      </div>
    </div>
  <% elsif current_user.admin? && !current_user.ninja? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info'%>
        </section>
        <%= link_to "View admin panel", admin_path, class: "btn btn-large btn-primary" %>
      </aside>
      <div class="span8">
        
      </div>
    </div>
  <% else %>
    <% if current_user.purchases.any? %>
      <div class="row">
        <aside class="span4">
          <section>
            <%= render 'shared/user_info'%>
          </section>
          <br>
          <% if @user.q_balance > 0 %>
            <section>
              <%= render 'shared/question_form' %>
            </section>
          <% else %>
            <section>
              <%= link_to "Buy more questions", plans_path, class: "btn btn-large btn-primary" %>
            </section>
          <% end %>
          <p>Want to be ninja? <%= link_to "Learn more.", new_ninja_path %><p>
        </aside>
        <div class="span8">
          <h3>Answered questions <i>(<%= @answered_items.count %>)</i></h3>
            <ol class="questions">
              <%= render 'shared/answered' %>
            </ol>
            <br>
            <h3>Pending questions <i>(<%= @pending_items.count %>)</i></h3>
            <ol class="questions">
              <%= render 'shared/pending' %>
            </ol>
        </div>
      </div>
    <% else %>
      <div class="center">
        <h1>Congratulations, <%= current_user.username %></h1> 
        <h2>You have entered the lair of the Physics Ninja.</h2>
      </div>
      <div class="row">
        <div class="span10 offset1">
          <span style="display:block; height: 10px;"></span>
          <h3>What we do</h3>
          <p>
            Give you clear, thorough, hilarious, and helpful answers to any physics question obstructing your path to sleep and/or fun.
          </p>
          <span style="display:block; height: 1px;"></span>
          <h3>What you get:</h3>
          <ul>
            <p>
              1. An answer within 24 hours.
              <br>
              2. Explanations you can actually understand and learn from.
              <br>
              3. The option to resolve your unique concerns in a private comments section.
            </p>
          </ul>
          <span style="display:block; height: 10px;"></span>
          <center>
            <%= link_to "Buy your first question", new_purchase_path(plan_id: 1), class: "btn btn-large btn-primary" %>
            <span style="display:block; height: 8px;"></span>
            <p>
              ...for the low low price of $5 (<%= link_to "WTF why??", why_we_charge_path %>)
            </p>
          </center>
          <p>
            Learn more about <%= link_to "how it works", how_it_works_path %>
          </p>
        </div>
        <div class="row">
          <div class="span12">
            <span style="display:block; height: 5px;"></span>
            <p>
            </p>
          </div>
          <aside class="span6">
            <div class="comment_unit">
              <b>Question:</b> 
              <p>A Porsche 944 Turbo has a rated engine power of 217 hp. 30% of the power is lost in the drive train, and 70% reaches the wheels. The total mass of the car and driver is 1500kg, and two-thirds of the weight is over the drive wheels. What is the maximum acceleration of the Porsche on a concrete surface where mu=1.00?</p>
            </div>
            <br>
            <p>
              <b>More examples</b> of the Ninja's powers:
              <br>
              <%= link_to "Elastic and inelastic collisions", example_path(id: 2) %>
              <br>
              <%= link_to "Dartboard kinematics", example_path(id: 3) %>
              <br>
              <%= link_to "Speed of light", example_path(id: 4) %>
              <br>
              <%= link_to "Particles in orbit", example_path(id: 5) %>
            </p>
            <br><br>
            <p>
              <b>Learn more</b> about the Ninja:
              <br>
              <%= link_to "How does it work?", how_it_works_path %>
              <br>
              <%= link_to "Why do we charge?", why_we_charge_path %>
              <br>
              <%= link_to "Ninja Code of Honor", ninja_code_path %>
            </p>
            <br><br>
            <p>Want to be ninja? <%= link_to "Learn more.", new_ninja_path %><p>
          </aside>
          <div class="span6">
            <div class="response_content">
              <b>Answer: </b>
              <p>The Porsche will reach its maximum acceleration when the force driving it (F_d) is as large as possible. This force F_d reaches a maximum when it is exactly equal to the force of friction on wheels (F_f). This is because if F_d were greater than F_f, the Porsche's wheels would just spin and the car would go nowhere! So at maximum acceleration, you have:</p>
              <p>F_d = F_f</p>
              <p>The driving force of the car at the maximum acceleration (a_max) is given by Newton's second law:</p>
              <p>F_d = m*(a_max)</p>
              <p>Meanwhile, the force of friction is:</p>
              <p>F_f = (mu)*F_N</p>
              <p>where the normal force F_N is the normal force on the drive wheels. Since 2/3 of the total mass is over the drive wheels, the friction force is then:</p>
              <p>F_f = (mu)*(2/3)*m*g</p>
              <p>Setting F_d = F_f gives:</p>
              <p>m*(a_max) = (mu)*(2/3)*m*g</p>
              <p>The m's cancel, so:</p>
              <p>a_max = (mu)*(2/3)*g</p>
              <p>and you can solve for a_max.</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="center hero-unit">
    <h1>Physics Ninja</h1>
    <h2>On-demand answers to any physics question</h2>
    <h3>Ready to begin?</h3>
    <%= link_to "Enter", signup_path, class: "btn btn-large btn-primary" %>
    <br><br>
    <center><p><font size=3>
      Already initiated? <%= link_to "Sign in", signin_path %>
    </p></center></font>
  </div>
  <ul>
    <b>The Physics Ninja has been endorsed by the greatest scientists across spacetime:</b>
  </ul>
  <ul>
    "I love the Physics Ninja!!!!"
    <br><i>Marie Curie, Nobel Laureate in physics and chemistry</i>
  </ul>
  <ul>
    "I had nooo clue what was happening with my physics homework before I discovered the Physics Ninja! Now, I totally understand everything."
    <br><i>Johannes Kepler, Astronomer & physicist</i>
  </ul>
  <ul>
    "Even I can admit: The Ninja's got some sick moves."
    <br><i>Isaac Newton, Physicst & mathematician</i>
  </ul>
<% end %> 

app/views/static_pages/howitworks.html.erb
<% provide(:title, 'How it works') %>
<% content_for :head do %>
  <meta name = "description" content = "On-demand answers to any physics question. Get high-quality help on homework with explanations and solutions you can actually understand!" />
  <meta name = "keywords" content = "physics, homework, help, questions, answers, solutions, tutor, tutoring" />
<% end %>
<div class="center">
	<h1>How it works</h1>
	<h2>The Ninja from A to Z</h2>
</div>
<div class="row">
	<div class="span10 offset1">
		<h3>The Protocol</h3>
		<p>
			<b>1. An answer within 24 hours</b> 
			<ul>Ask and you shall receive. Give us a problem, we explain the solution. 24 hours starts from the moment (timestamped!) you ask the question.</ul>
		</p>
		<p>
			<b>2. Step-by-step instruction</b> 
			<ul>Other sites answer questions with walls of equations, and they don't explain how they figured out which concepts to apply and why. You might get the answer from them, but you won't learn from it. We give clear, accessible explanations that you can actually apply to future problems (say, exams!).</ul>
		</p>
		<p>
			<b>3. The option to resolve concerns/clarification in a private comments section</b> 
			<ul>The Ninja will work with you one-on-one for as long as it takes to make sure you get the answer you need. Once you submit a question, you'll be able to leave comments for the Ninja. Even after we've given you an answer, we'll continue to work with you until you feel like you fully understand.</ul>
		</p>
		<span style="display:block; height: 10px;"></span>
		<h3>The Rules</h3>
		<ul>
			<li>
				<p>
					<b>Don't cheat</b>
					<br>
					We're pretty good at spotting questions lifted from take-home exams. We're here to help you learn--not to help you cheat. So don't ask us to. Follow the <%= link_to "Ninja Code", ninja_code_path %>.
				</p>
			</li>
			<li>
				<p>
					<b>Don't double dip</b>
					<br>
					In the spirit of ingenuity, you might be tempted to try to get around paying for questions--say, by submitting them through the comments section or emailing them to our support center. But nobody likes a double dipper. Don't be that person--we won't answer.
				</p>
			</li>
			<li>
				<p>
					<b>Do hold us accountable</b>
					<br>
					Our commitment is to give you answers that meet your needs. The Ninja will interact with you personally in the comments if you want to get more clarification, explore a problem for a different angle, or just chat. If an answer isn't working for you or something goes wrong, please let us know via <%= link_to "ninja support", support_path %>.
				</p>
			</li>
		</ul>
		<span style="display:block; height: 10px;"></span>
		<h3>FAQs</h3>
		<ul class="questions">
			<li>
				<p>
					Q: Okay, I'm here--what do I do?
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: First, <%= link_to "buy a question", plans_path %> (the first one is offered at a <%= link_to "discount", new_purchase_path(plan_id: 1) %>). Then just <%= link_to "ask!", root_path %>
						<br>
						Check back on your <%= link_to "home page", root_path %> to see your answer within 24 hours (usually less)--just click "View answer" under your question. By clicking on questions, you can also leave comments before or after your answer has been posted if you need to add something or ask for more info.
					</span>
				</p>
			</li>
			<li>
				<p>
					Q: Who can use The Physics Ninja?
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: Anyone and everyone. We answer high school, college, and general curiosity physics questions.
					</span>
				</p>
			</li>
			<li>
				<p>
					Q: What kinds of questions can I ask?
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: You can send us a question directly from a homework assignment or textbook, or ask something more general. We can walk you through a tough derivation or just chat about the speed of light. We do it all!
					</span>
				</p>
			</li>
			<li>
				<p>
					Q: Why is it so expensive? 
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: The Physics Ninja gives you more than just an answer: In addition to providing clear explanations, we also work with you one-on-one for as long as it takes to help you understand. We charge what we think is fair based on that level of quality (more on that <%= link_to "here", why_we_charge_path %>).
					</span>
				</p>
			</li>
			<li>
				<p>
					Q: How is my credit card information stored? 
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: To ensure a high level of security, we use <%= link_to "stripe", "http://www.stripe.com", target: '_blank' %> to handle all of our transactions. All credit card numbers are transferred over SSL and are encrypted on a disk with AES-256.
					</span>
				</p>
			</li>
			<li>
				<p>
					Q: Who are you? 
					<span style="display:block; height: 5px;"></span>
					<span class="response_content">
						A: We are the heroes physics deserves, the ones the Internet needs right now. We are the silent guardians, the watchful protectors, the Dark Knights. We are The Physics Ninja.
						<br><br>
						Come on, what would the fun be if we told you?
					</span>
				</p>
			</li>
		</ul>
	</div>
</div>

app/views/static_pages/ninjacode.html.erb
<% provide(:title, 'Ninja Code') %>
<div class="center">
	<h1>Ninja Code</h1>
	<h2>Integrity, Accessibility, Quality</h2>
</div>
<div class="row">
	<div class="span10 offset1">
		<p>
			Ask questions. 
			<br>
			Be curious.
			<br>
			Don't cheat. 
	</div>
</div>

app/views/static_pages/support.html.erb
<% provide(:title, 'Support') %>
<h1>Support</h1>
<p>
	Something wrong? Email us at <a href="mailto:support@c4online.com">ninja support</a>.
</p>
	<span style="display:block; height: 10px;"></span>
<font size="2">
	* Note: Emailing your physics questions to the help-line is likely to unleash the wrath of the Ninja. And trust us, you don't want to anger a physics expert, lest you come face-to-face with a seriously massive block sliding down an inclined plane...
</font>

app/views/static_pages/unsubscribe.html.erb
<% provide(:title, 'Unsubscribe') %>
<div class="center">
	<h1>Unsubscribe</h1>
	<h2>You have successfully unsubscribed!</h2>
</div>

app/views/static_pages/whywecharge.html.erb
<% provide(:title, 'Why we charge') %>
<div class="center">
	<h1>WTF?</h1>
	<h2>Why are you charging me?</h2>
</div>
<div class="row">
	<div class="span10 offset1">
		<p>
			The ninja's gotta eat. Also, we need new nunchucks.
			<br><br>
			You've seen the other resources out there. You can put your question into Google and rely on the credibility of Yahoo Answers (yikes). You can pay upfront to view a bunch of questions on Chegg, and get stuck with half-assed responses that don't address your confusions (ugh). Or you can shell out for a tutor and survive on cereal for the rest of the semester (not healthy!).
			<br><br>
			Learning is tough, and good instruction takes resources. We're keeping our prices as low as possible by offering personal instruction in question-by-question chunks. The Ninja is more than just a Q+A service: we give you the one-on-one attention you need to get to the root of your question and set you up for long-term success.
		</p>
	</div>
</div>