config/routes.rb
Physicsninja::Application.routes.draw do
  resources :users do
    resources :purchases, only: :index
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :questions do
    resources :responses, only: [:create, :index, :destroy]
    resources :comments,  only: [:create, :index, :destroy]
  end
  resources :plans,       only: :index
  resources :purchases,   only: [:show, :new, :create, :destroy]
  resources :ninjas,      only: [:new, :create]

  resources :examples,    only: :show

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/buy',     to: 'plans#index'

  match '/pending',   to: 'questions#pending'
  match '/answered',  to: 'questions#answered'
  match '/commented', to: 'questions#commented'

  match 'users/:id/toggle_admin', to: 'users#toggle_admin'
  match 'users/:id/toggle_ninja', to: 'users#toggle_ninja'
  match 'users/:id/give_q',       to: 'users#give_q'

  match '/support', to: 'static_pages#support'
  match '/about',   to: 'static_pages#about'
  match '/admin',   to: 'static_pages#admin'
  match '/how_it_works',   to: 'static_pages#howitworks'
  match '/why_we_charge',   to: 'static_pages#whywecharge'
  match '/ninja_code',   to: 'static_pages#ninjacode'
  match '/unsubscribe',   to: 'static_pages#unsubscribe'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    	<li><%= link_to "How it works", how_it_works_path %></li>
    	<li><%= link_to "About", about_path %></li>
    	<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "physics ninja", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <% if current_user.ninja? %>
              <li><%= link_to "My Answers", user_path(current_user) %></li>
            <% end %>
          <% end %>
          <% if signed_in? %>
            <% if !current_user.ninja? && !current_user.admin? %>
              <li><%= link_to "Buy", plans_path %></li>
            <% end %>
          <% end %>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Help<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "How it works", how_it_works_path %></li>
                <li><%= link_to "Why we charge", why_we_charge_path %></li>
                <li><%= link_to "Ninja Code", ninja_code_path %></li>
                <li><%= link_to "Support", support_path %></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Purchase History", user_purchases_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%# Make stripe java tag conditional so it only shows up on payment pages %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <%= render 'layouts/shim' %>
    <% if content_for? :head %>
      <%= yield :head %>
    <% end %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>